-- Load stuff
require("mylordkaz.lazy")
require("mylordkaz.remap")
require("mylordkaz.settings")
require("mylordkaz.plugins.telescope")
require("mylordkaz.plugins.treesitter")
require("mylordkaz.plugins.lsp")
require("mylordkaz.plugins.nvimtree")
require("mylordkaz.plugins.gitsigns")
require("mylordkaz.plugins.autopairs")
require("mylordkaz.plugins.solidity")
